CREATE TABLE `agent_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` varchar(64) NOT NULL,
	`agentId` varchar(64) NOT NULL,
	`agentName` varchar(128) NOT NULL,
	`status` enum('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
	`inputData` json,
	`outputData` json,
	`errorMessage` text,
	`durationMs` int,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `agent_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` varchar(64) NOT NULL,
	`scenarioType` varchar(64),
	`borrowerName` varchar(255) NOT NULL,
	`borrowerAge` int,
	`borrowerEmail` varchar(320),
	`borrowerPhone` varchar(32),
	`borrowerSsn` varchar(16),
	`employerName` varchar(255),
	`jobTitle` varchar(255),
	`yearsEmployed` float,
	`annualIncome` float,
	`employmentType` varchar(64),
	`loanAmount` float NOT NULL,
	`loanTermMonths` int NOT NULL,
	`loanPurpose` varchar(64),
	`downPayment` float,
	`propertyAddress` varchar(512),
	`propertyType` varchar(64),
	`propertyValue` float,
	`propertySquareFeet` int,
	`propertyBedrooms` int,
	`propertyBathrooms` float,
	`propertyYearBuilt` int,
	`propertyState` varchar(4),
	`propertyZip` varchar(16),
	`creditScore` int,
	`existingDebtsMonthly` float,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`decision` enum('approved','conditional_approval','denied','review_required'),
	`decisionRationale` text,
	`interestRate` float,
	`monthlyPayment` float,
	`approvedAmount` float,
	`applicationProcessorResult` json,
	`creditAnalyzerResult` json,
	`collateralValuatorResult` json,
	`complianceCheckerResult` json,
	`riskScorerResult` json,
	`decisionEngineResult` json,
	`documentationGeneratorResult` json,
	`processingStartedAt` timestamp,
	`processingCompletedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `applications_applicationId_unique` UNIQUE(`applicationId`)
);
--> statement-breakpoint
CREATE TABLE `audit_trail` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` varchar(64) NOT NULL,
	`eventType` varchar(128) NOT NULL,
	`agentId` varchar(64),
	`agentName` varchar(128),
	`description` text NOT NULL,
	`details` json,
	`severity` enum('info','warning','error','critical') NOT NULL DEFAULT 'info',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_trail_id` PRIMARY KEY(`id`)
);
