CREATE TABLE `dir_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` varchar(64) NOT NULL,
	`eventType` enum('announce','discover','resolve','heartbeat') NOT NULL,
	`agentId` varchar(128) NOT NULL,
	`agentDid` varchar(512) NOT NULL,
	`queryCapability` varchar(256),
	`queryDomain` varchar(256),
	`resultCount` int,
	`oasfRecord` json,
	`latencyMs` int,
	`success` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dir_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `otel_spans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` varchar(64) NOT NULL,
	`traceId` varchar(64) NOT NULL,
	`spanId` varchar(64) NOT NULL,
	`parentSpanId` varchar(64),
	`operationName` varchar(256) NOT NULL,
	`serviceName` varchar(128) NOT NULL,
	`agentId` varchar(128),
	`status` enum('ok','error','unset') NOT NULL DEFAULT 'ok',
	`startTimeMs` int NOT NULL,
	`endTimeMs` int,
	`durationMs` int,
	`attributes` json,
	`events` json,
	`kind` enum('server','client','producer','consumer','internal') NOT NULL DEFAULT 'internal',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `otel_spans_id` PRIMARY KEY(`id`),
	CONSTRAINT `otel_spans_spanId_unique` UNIQUE(`spanId`)
);
--> statement-breakpoint
CREATE TABLE `slim_messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` varchar(64) NOT NULL,
	`messageId` varchar(64) NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`sourceAgentId` varchar(128) NOT NULL,
	`sourceAgentDid` varchar(512) NOT NULL,
	`destinationAgentId` varchar(128) NOT NULL,
	`destinationAgentDid` varchar(512) NOT NULL,
	`channel` varchar(512) NOT NULL,
	`pattern` enum('request-reply','pub-sub','fire-and-forget','streaming') NOT NULL,
	`encryptionAlgo` varchar(64) NOT NULL DEFAULT 'MLS',
	`identityVerified` boolean NOT NULL DEFAULT true,
	`signatureValid` boolean NOT NULL DEFAULT true,
	`payloadSchema` varchar(512) NOT NULL,
	`payloadSizeBytes` int,
	`payloadPreview` text,
	`correlationId` varchar(64),
	`hopCount` int NOT NULL DEFAULT 1,
	`latencyMs` int,
	`status` enum('sent','delivered','acknowledged','failed') NOT NULL DEFAULT 'sent',
	`sentAt` timestamp NOT NULL DEFAULT (now()),
	`deliveredAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `slim_messages_id` PRIMARY KEY(`id`),
	CONSTRAINT `slim_messages_messageId_unique` UNIQUE(`messageId`)
);
