import type { ApplicationInput } from "./pipeline";

export interface TestScenario {
  id: string;
  name: string;
  description: string;
  expectedDecision: string;
  badge: string;
  data: Omit<ApplicationInput, "applicationId">;
}

export const TEST_SCENARIOS: TestScenario[] = [
  {
    id: "prime-borrower",
    name: "Prime Borrower",
    description:
      "High credit score, stable employment, low DTI, strong down payment. Expected to receive full approval at best available rate.",
    expectedDecision: "approved",
    badge: "Approved",
    data: {
      borrowerName: "Alexandra Chen",
      borrowerAge: 38,
      borrowerEmail: "a.chen@example.com",
      borrowerPhone: "555-0101",
      employerName: "Apex Technologies Inc.",
      jobTitle: "Senior Software Engineer",
      yearsEmployed: 8,
      annualIncome: 185000,
      employmentType: "Full-time",
      loanAmount: 480000,
      loanTermMonths: 360,
      loanPurpose: "Purchase",
      downPayment: 120000,
      propertyAddress: "742 Evergreen Terrace, Austin, TX 78701",
      propertyType: "Single Family",
      propertyValue: 600000,
      propertySquareFeet: 2800,
      propertyBedrooms: 4,
      propertyBathrooms: 3,
      propertyYearBuilt: 2018,
      propertyState: "TX",
      propertyZip: "78701",
      creditScore: 780,
      existingDebtsMonthly: 650,
    },
  },
  {
    id: "good-borrower",
    name: "Good Borrower",
    description:
      "Good credit, moderate DTI, smaller down payment. Expected conditional approval with standard documentation requirements.",
    expectedDecision: "conditional_approval",
    badge: "Conditional",
    data: {
      borrowerName: "Marcus Williams",
      borrowerAge: 32,
      borrowerEmail: "m.williams@example.com",
      borrowerPhone: "555-0202",
      employerName: "Meridian Healthcare Group",
      jobTitle: "Registered Nurse",
      yearsEmployed: 4,
      annualIncome: 92000,
      employmentType: "Full-time",
      loanAmount: 320000,
      loanTermMonths: 360,
      loanPurpose: "Purchase",
      downPayment: 35000,
      propertyAddress: "1820 Maple Avenue, Charlotte, NC 28202",
      propertyType: "Townhouse",
      propertyValue: 355000,
      propertySquareFeet: 1900,
      propertyBedrooms: 3,
      propertyBathrooms: 2.5,
      propertyYearBuilt: 2012,
      propertyState: "NC",
      propertyZip: "28202",
      creditScore: 718,
      existingDebtsMonthly: 1100,
    },
  },
  {
    id: "denied",
    name: "Denied",
    description:
      "Poor credit score, very high DTI, minimal down payment. Expected denial due to multiple risk threshold violations.",
    expectedDecision: "denied",
    badge: "Denied",
    data: {
      borrowerName: "Robert Dawson",
      borrowerAge: 27,
      borrowerEmail: "r.dawson@example.com",
      borrowerPhone: "555-0303",
      employerName: "Quick Serve Retail",
      jobTitle: "Store Associate",
      yearsEmployed: 1,
      annualIncome: 38000,
      employmentType: "Part-time",
      loanAmount: 280000,
      loanTermMonths: 360,
      loanPurpose: "Purchase",
      downPayment: 8000,
      propertyAddress: "55 Oak Street, Detroit, MI 48201",
      propertyType: "Single Family",
      propertyValue: 290000,
      propertySquareFeet: 1400,
      propertyBedrooms: 3,
      propertyBathrooms: 1,
      propertyYearBuilt: 1978,
      propertyState: "MI",
      propertyZip: "48201",
      creditScore: 598,
      existingDebtsMonthly: 1450,
    },
  },
  {
    id: "compliance-trigger",
    name: "Compliance Trigger",
    description:
      "Application with patterns that trigger Fair Lending review and BSA/AML screening. Demonstrates compliance agent escalation workflow.",
    expectedDecision: "review_required",
    badge: "Review",
    data: {
      borrowerName: "Fatima Al-Rashid",
      borrowerAge: 45,
      borrowerEmail: "f.alrashid@example.com",
      borrowerPhone: "555-0404",
      employerName: "International Trading Co.",
      jobTitle: "Import/Export Manager",
      yearsEmployed: 2,
      annualIncome: 145000,
      employmentType: "Self-employed",
      loanAmount: 750000,
      loanTermMonths: 360,
      loanPurpose: "Purchase",
      downPayment: 250000,
      propertyAddress: "9900 Biscayne Blvd, Miami, FL 33138",
      propertyType: "Condominium",
      propertyValue: 1000000,
      propertySquareFeet: 2200,
      propertyBedrooms: 3,
      propertyBathrooms: 3,
      propertyYearBuilt: 2020,
      propertyState: "FL",
      propertyZip: "33138",
      creditScore: 705,
      existingDebtsMonthly: 2200,
    },
  },
  {
    id: "complex-application",
    name: "Complex Application",
    description:
      "Self-employed borrower with multiple income sources, co-borrower scenario, non-standard property. Requires multi-step review and additional documentation.",
    expectedDecision: "conditional_approval",
    badge: "Conditional",
    data: {
      borrowerName: "Priya & Arjun Sharma",
      borrowerAge: 41,
      borrowerEmail: "sharma.family@example.com",
      borrowerPhone: "555-0505",
      employerName: "Sharma Consulting LLC (Self-employed)",
      jobTitle: "Business Owner / Consultant",
      yearsEmployed: 6,
      annualIncome: 220000,
      employmentType: "Self-employed",
      loanAmount: 620000,
      loanTermMonths: 360,
      loanPurpose: "Purchase",
      downPayment: 155000,
      propertyAddress: "3401 Pacific Coast Hwy, Malibu, CA 90265",
      propertyType: "Single Family",
      propertyValue: 775000,
      propertySquareFeet: 3200,
      propertyBedrooms: 4,
      propertyBathrooms: 3.5,
      propertyYearBuilt: 2005,
      propertyState: "CA",
      propertyZip: "90265",
      creditScore: 742,
      existingDebtsMonthly: 3100,
    },
  },
];

export function getScenarioById(id: string): TestScenario | undefined {
  return TEST_SCENARIOS.find((s) => s.id === id);
}
